### ISSUE TITLE
Uses Redis store (not memory) by default

### ISSUE THREAD

**Issue by philmander** [englercj/mongoose-cache-manager#4]
On https://github.com/englercj/mongoose-cache-manager/blob/master/lib/index.js#L54 it tries to create redis store even if the `store` option is set to memory. I can't see any way to use a memory store

**Comment by englercj** [comment]
This was just an experiment, never meant to actually be used anywhere. A pure query cache isn't even very useful for most non-trivial applications. Feel free to fork and do whatever you want with this, but it is more or less just code examples.
